---
kind: pipeline
name: build container
steps:

- name: debug
  image: quay.io/centos/amd64:stream9
  commands:
    - env
    - cat /etc/resolv.conf
    - ping -c1 google.com
    - nslookup gogle.com

- name: build-container  
  image: plugins/docker
  settings:
    dry_run: true
    repo: harbor.apps.infra.hahl.id.au/hahl.id.au/image-build-tools
    registry: harbor.apps.infra.hahl.id.au
    tags:
      - "build"
  when:
    branch:
      - master
      - main
trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
name: promote
steps:

- name: build-tags
  image: alpine
  commands:
    - env
    - echo -n "$(date +'%Y%m%d%H%M'), latest, ${DRONE_DEPLOY_TO}" > .tags

- name: build-container  
  image: plugins/docker
  settings:
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password
    repo: harbor.apps.infra.hahl.id.au/hahl.id.au/image-build-tools
    registry: harbor.apps.infra.hahl.id.au
trigger:
  event:
  - promote
